### ISSUE TITLE
How to link either of the Signin option after initial registration.

### ISSUE THREAD

**Issue by yomp-admin** [passlock-dev/svelte-passkeys#6]
If I register with Social login how can I link the passkey or vice-versa

**Comment by thobson** [comment]
Currently you can’t link accounts, although I have it on my TODO list. I’m still debating whether to handle it in the SvelteKit template (easiest/quickest) vs Passlock core. I’m favouring the second option. I’ll keep this ticket open and update with progress.

**Comment by thobson** [comment]
Done via the Passlock core client
